# Generated by Django 5.2.3 on 2025-06-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('ai_response', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
